PCSX2/pcsx2_patches

- .github/workflows/pack_patches.yml
Create and publish .zip files that https://github.com/PCSX2/pcsx2/pull/6777 can then pull into the archive.
> Pack and upload zips on build time

- cheats_ws/02F4B541.pnach
Fixes the Battlefront 2 WS patch by removing a bad code.
> WS: Fix Battlefront 2 WS patch

- cheats_ws/9BC05316.pnach
Seems to cause random camera movements when passing or shooting.
> WS: Remove Redcard 20-03 NTSC WS patch

- cheats_ws/2BDA8ADB.pnach
> WS: Comment out WS patch for Project Snowblind

- cheats_ws/CBDF678C.pnach
Has SPS issues at several locations:
Fixed:
Was caused by broken render patch.
> WS: Comment out patch Sonic Riders - Zero Gravity

- cheats_ni/F9D5C6A6.pnach
This PR adds no-interlace patch for `Shutokou Battle 0` .
> NI: Add NI patch for Tokyo Xtreme Racer 0 (J)

- cheats_ni/DD70E38F.pnach
- cheats_ni/F9D5C6A6.pnach
make `Tokyo Xtreme Racer 0` NI patch a bit simpler
and add `Tokyo Xtreme Racer 3` NI patch
> NI: Add Shutokou Battle 01 patch and modify Shutokou Battle 0 patch

- cheats_ws/3EEB02D9.pnach
Ape Escape 3 (Chinese language Version) Widescreen hack 16:9
> WS:Add ws patch Zhuo Hou La 3

- cheats_ni/1C087362.pnach
Adds no interlacing patch for Racing Battle - C1 Grand Prix
> NI: Add Racing Battle - C1 Grand Prix (SLPM-65897) patch

- cheats_ni/54854C71.pnach
- cheats_ni/F7CD277C.pnach
- cheats_ws/F7CD277C.pnach
Adds progressive scan patch for the Japanese version and a 60hz progressive scan patch to the European version. Also cleaned up old and unneeded glitch patches in the Japanese version widescreen patch.
> NI: Add Maken Shao patches.

- cheats_ws/327053E8.pnach
The patch crashes the emu.
Issue: https://github.com/PCSX2/pcsx2/issues/8195
> WS: Comment/disable Darkwatch patch.

- cheats_ws/AEEC4D5C.pnach
> correct Giants Citizen Kabuto patch

- cheats_ni/230CB71D.pnach
Update offsets for v2.00 of the game.
> NI: Add Soul Reaver 2 (v2.00)

- cheats_ws/94A82AAA.pnach
Applies to: 94A82AAA.pnach
I updated the FMV fix to properly scale to ratio instead of cropping like Nemesis2000 did in the past. The community has also made a ton more changes since that need to be pulled in as well.
This also removes the persona artwork fixes as it's not a good fix and causes portraits to bend.
> Pull in Latest WS Changes for Persona 3 FES USA

- cheats_ws/53591072.pnach
- cheats_ws/55EDA5A0.pnach
- cheats_ws/BD9E8B57.pnach
- cheats_ws/CFC63DFF.pnach
- cheats_ws/D2F77DF2.pnach
Adds Rayman Raving Rabbids widescreen patches, updates Rayman Revolution patches with the addition of a JP version patch as well.
> Add/Update Rayman 16:9 patches

- cheats_ni/9C712FF0.pnach
- cheats_ni/EDE4FE64.pnach
- cheats_ws/B4976DAF.pnach
- cheats_ws/EDE4FE64.pnach
Adds more 16:9 and no-interlacing patches for regional versions of Jak games that didn't have them.
> Add more Jak patches for JP/PAL regions

- cheats_ws/82E1D0EA.pnach
> WS : disable broken WS patch

- cheats_ws/88A808FA.pnach
Similar fix potentially needed for 2002, 2003 (if not more), will try and look into :)
> WS: Fixed PGA Tour 2005 16:9 patch & added 21:9

- patches/SLES-52541_A1B3F232.pnach
- patches/SLES-52541_B440A8FE.pnach
- patches/SLPM-55292_9E18263C.pnach
- patches/SLPM-65984_60FE139C.pnach
- patches/SLUS-20946_2C6BE434.pnach
- patches/SLUS-20946_399A49CA.pnach
Removes the ugly ghosting on things with one simple patch.
> Patches: Add remove radiosity patch to GTA SA

- patches/SLES-52541_A1B3F232.pnach
Adds a 50 fps patch for GTA SA PAL and amends an exceptionally long description into a short author section.
> Patches: Add 50 fps patch to PAL GTA San Andreas

- patches/C220951A.pnach
- patches/EC33CA0D.pnach
This is the de-interlace patch for Gran Turismo Concept 2001 TOKYO and Kaido Battle Touge no Densetsu
> New Patches

- patches/SLPM-65233_08995DEE.pnach
- patches/SLUS-20484_08995DEE.pnach
- patches/SLUS-20627_08995DEE.pnach
All the same CRC, got missed once we added the serials
> Add missing widescreen patches for DMC2 US + J Lucia Disc

- patches/SCES-50490_A39517AB.pnach
- patches/SCES-50492_941BB7D9.pnach
- patches/SLES-54215_1AFD7469 .pnach
- patches/SLUS-21400_1AFD7469.pnach
> Fix up some more patches which were used for multiple versions

- patches/SLES-51838_1DB1A6C6.pnach
- patches/SLUS-20866_7884CDB0.pnach
Updates the syntax, adds No-Interlacing codes, and replicates the Black Bars code from Kick Buttix to XXL.
> Patches for Asterix & Obelix XXL + Asterix & Obelix Kick Buttix

- patches/SLPM-67519_D2F77DF2.pnach
- patches/SLUS-20693_2C1173B0.pnach
- patches/SLUS-20902_57818AF6.pnach
> Patches :  some missed patches

- patches/SCUS-97610_72326E67.pnach
> Widescreen patch for Hot Shots Tennis NTSC-U

- patches/SLES-52569_6E51213C.pnach
> Widescreen patch for Spyro A Hero's Tail PAL

- patches/SLES-54087_9CD9C449.pnach
Suikoden V updated widescreen patch with fixed reflections.
> Update Suikoden V SLES-54087_9CD9C449.pnach

- patches/SLES-52023_FE419424.pnach
- patches/SLES-53812_A38C6B77.pnach
- patches/SLES-54135_D693D4CF.pnach
- patches/SLES-54622_B3AD1EA4.pnach
- patches/SLES-54819_887AD3A0.pnach
- patches/SLUS-20827_38DEA143.pnach
- patches/SLUS-21155_9AC20A5B.pnach
- patches/SLUS-21423_7EA439F5.pnach
- patches/SLUS-21590_4F32A11F.pnach
- patches/SLUS-21613_3B0ADBEF.pnach
All the patches have been tested and work fine.
> Patches: Add 50/60 FPS patches to KND, GTA Stories and Manhunts and tidy up format

- patches/SLUS-20500_E169BAF8.pnach
Made by kozarovv to do the same effect as the CRC hack but not being a hardcoded mess.
- Before:
- After:
> Patches: Backport Aggressive CRC-Red Dead Revolver

- patches/SLUS-20811_CB99CD12.pnach
- patches/SLUS-21891_67655A22.pnach
This PR adds 60 FPS patches to G-Force and NFS Underground.
Tested by me.
> 60 FPS Patches Additions

- patches/SLES-50677_7DE3F9E8.pnach
CRC doesn't match so I don't trust that the patch is correct.
Fixes #134
> Remove patch for Shadow Hearts with wrong serial

- patches/SLUS-21355_60A42FF5.pnach
60 fps patch for midnight club 3 dub remix.
> Patch: Midnight Club 3 Dub Remix 60 fps patch

- patches/SLUS-21143_976EA156.pnach
I've played through the whole game with the patch and had no issues, although the main menu FMV is double speed but not game breaking of course.
> Added Star Wars Episode III - Revenge of the Sith NTSC 60 FPS patch.

- patches/SCES-50409_3242590D.pnach
> WS: fix up MotoGP 2 patch

- patches/SLES-53557_692CBA8E.pnach
- patches/SLES-53558_1FA82CDF.pnach
- patches/SLES-53559_CA2A1B04.pnach
- patches/SLES-53857_805C3B3A.pnach
- patches/SLUS-21267_270F8C03.pnach
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Add NFS MW brown filter patches

- patches/SLUS-21351_0518D274.pnach
Missed this one when doing my last pr (#201)
> Add NFS MW Black Edition brown filter patch

- patches/SLUS-20733_28270F7D.pnach
https://forums.pcsx2.net/Thread-Widescreen-patch-not-working-Castlevania-Lament-of-Innocence
> Working WS pnach for Castlevania: Lament of Innocence - NTSC-U

- patches/SLUS-21208_21278F5B.pnach
- patches/SLUS-21295_21278F5B.pnach
Removes two filters that are problematic with hardware upscaling. Cheats by TechieSaru.
> Patch files for Tony Hawk's American Wasteland

- patches/SLES-50335_52638022.pnach
- patches/SLES-50335_7DB392C5.pnach
- patches/SLES-50339_7DB392C5.pnach
- patches/SLES-50795_4F5579D3.pnach
- patches/SLES-50808_3AC738AA.pnach
- patches/SLES-51333_5BE3F481.pnach
- patches/SLES-51354_960FFA6A.pnach
- patches/SLES-51507_EB25115F.pnach
- patches/SLES-52039_BE408EFF.pnach
- patches/SLES-52587_95CFD603.pnach
- patches/SLES-52644_A1FD63D6.pnach
- patches/SLES-52801_614F4CF4.pnach
- patches/SLES-52805_614F4CF4.pnach
- patches/SLES-53139_14274DC3.pnach
- patches/SLES-53158_E38A0AB6.pnach
- patches/SLES-53501_02F4B541.pnach
- patches/SLES-53618_B1AC3BEB.pnach
- patches/SLES-54169_761CABB3.pnach
- patches/SLES-54755_2609B672.pnach
- patches/SLES-54756_F453BCD9.pnach
- patches/SLES-55470_4F82849C.pnach
- patches/SLES-55520_9E36E023.pnach
- patches/SLUS-20109_3A09007C.pnach
- patches/SLUS-20379_29BA2F04.pnach
- patches/SLUS-21047_ECFBAB36.pnach
- patches/SLUS-21205_9FA0A1B0.pnach
They have been tested and work without problem. I have also corrected the main crcs that I have found so that there are no conflicts with the secondary one
> add 60fps patches, widescreen and updates

- patches/SLES-51286_EE3180F4.pnach
- patches/SLUS-20337_16FB9855.pnach
> WS : disable some patches

- patches/SLUS-21016_C1B141D6.pnach
> Patches: Disable 25 to life widescreen

- patches/SCES-55573_3C967DB9.pnach
- patches/SCUS-97654_773D2835.pnach
- patches/SLUS-20941_F17AF8BD.pnach
Adds tested 60fps patches for two games
> MotorStorm and Hulk 60fps Patches

- SLUS-20910_5D0244D3.pnach
Add patches for changing aspect ratio and disabling 16:9 edge borders (main menu and paint shop).
> Test Drive - Eve of Destruction Patches

- patches/SLUS-21048_9DE65987.pnach
> Evil Dead 60fps patch

- patches/SLUS-20910_5D0244D3.pnach
I mistakenly put it in the main folder instead of the patches folder
> Move Test Drive - Eve of Destruction Patches to "patches" Folder

- patches/SLUS-21242_D224D348.pnach
- patches/SLUS-21596_8C9576A1.pnach
**[Progressive Scan] always ask for 480p**
**[MPH to KPH] Miles per hour to Kilometres per hour speedometer**
**[Widescreen 16:9 and 21:9] new entire patch by SuperType1 (https://www.youtube.com/watch?v=fXY97XEIQQ8)**
**[60 FPS Menus and Crashes] 60fps menus and crash cam**
> Burnout Revenge/Dominator Patches Update

- patches/SLUS-21731_A8D83239.pnach
Adds 60fps to silent hill origins
The game has been completed more than 2 times and there doesn't seem to be any bugs.
> Silent Hill Origins 60 FPS

- patches/SLES-50111_04489C11.pnach
- patches/SLUS-20148_8CB179A6.pnach
- patches/SLUS-21846_FB236A46.pnach
Disables Sonic Unleasheds NTSC-U WS patch as it causes crashing and disables ZoE 1 WS patch as it causes graphical issues with certain attacks.
> Patches: Various fixes

- patches/SLPS-25815_F28D21F1.pnach
https://forums.pcsx2.net/Thread-A-widescreen-patch-is-breaking-JPN-Tenkaichi-3
> Working WS hack for Tenkaichi 3 (NTSC-J)

- patches/SCES-50006_04F9D87F.pnach
- patches/SLES-50672_4A9D8E01.pnach
- patches/SLES-50821_22E91837.pnach
- patches/SLES-51071_8AEE00C6.pnach
- patches/SLES-51227_54AD76D7.pnach
- patches/SLES-51466_A7705A52.pnach
- patches/SLES-52002_144CC35B.pnach
- patches/SLES-52149_AB82114E.pnach
- patches/SLES-52150_BCAD1E8A.pnach
- patches/SLES-52187_F59FF56B.pnach
- patches/SLES-52384_9D87F3AF.pnach
- patches/SLES-53007_4C4D7072.pnach
- patches/SLES-53154_26420115.pnach
- patches/SLES-53667_BBB8392E.pnach
- patches/SLES-53825_23B754F4.pnach
- patches/SLES-53826_ABE3FDEA.pnach
- patches/SLES-53908_05177ECE.pnach
- patches/SLES-54674_A629A376.pnach
- patches/SLUS-20035_773A8DAB.pnach
- patches/SLUS-20491_E349C1D4.pnach
- patches/SLUS-20766_9A51B627.pnach
Allegedly using ";" as comment-mark can cause crash.
> Change ";" into "//" as comment-mark.

- patches/SLPM-65495_6232D656.pnach
> Patches: Cleanup

- patches/SLES-52569_6E51213C.pnach
- patches/SLUS-20884_94C56923.pnach
> WS: fix up some patches

- patches/SLUS-20974_D7273511.pnach
Causes TLB misses on game boot.
> Patches: Disable SMT DDS WS Patch

- patches/SLPS-20055_59D0C07E.pnach
- patches/SLUS-21019_34DC8778.pnach
Adds no-interlacing patches for Technic Beat and Technictix, closes #326
Patches tested
> No-Interlacing: Technic Beat and Technictix

- patches/SCUS-97199_CE4933D0.pnach
Didn't fully disable it originally and it keeps causing confusion. woopsie
> WS: Fully disable R&C 1 patch

- patches/SLUS-21782_DEDC3B71.pnach
> WS:fix broken patch

- patches/SCUS-97328_77E61C8A.pnach
More patches for GT4 collected from: https://github.com/AeroWidescreen/PCSX2-Cheats/tree/main
> Patches: Bring over more GT4 patches

- patches/SLUS-20954_E798B2D5.pnach
> WS: Disable Hot Wheels STC WS patch

- patches/SLPM-66363_AE22A564.pnach
- patches/SLPS-25377_B476ED7A.pnach
Breaks menu cursor alignment. Relevant issue: https://github.com/PCSX2/pcsx2/issues/11288
> Patches: Disable DQ YYMD WS Patch

- patches/SLUS-20500_E169BAF8.pnach
Been playing through the whole game with this and having no issues, so decided to push it here.
> Red Dead Revolver [SLUS-20500_E169BAF8] additional patches and correcting gametitle

- patches/PBPX-95503_8AA991B0.pnach
- patches/SCUS-97102_85AE91B3.pnach
The author of the NI hack is asasega.
https://forums.pcsx2.net/Thread-No-interlacing-codes?pid=589919#pid589919
> Specifying asasega as author of a NI hack

- patches/SLUS-20573_A4B3D285.pnach
The previous patch did not work and I have replaced it with the improved patch.
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=612246#pid612246
> Update SLUS-20573 WS Fix

- patches/SLPM-65268_A62EBC2C.pnach
This is copy/paste of [SLPM-65268_B9FA5764.pnach](https://github.com/PCSX2/pcsx2_patches/blob/9f305ec89e0c8c49c3b2c9ff7da825a8a0152af3/patches/SLPM-65268_B9FA5764.pnach)
I have finished few races and all seems to be fine! Useful for RA as the set requires 2.00 version of the game.
> WS: Initial D - Special Stage (2.00)

- patches/SLES-54308_38A5588B.pnach
> WS: Disable Phantasy Star Universe WS patch

- patches/SLES-51058_54854C71.pnach
> no-interlacing :stop Maken Shao from  crashing on boot

- patches/SCES-53202_1F88BECD.pnach
- patches/SLES-54221_37E36C6D.pnach
People really need to test these things on god.
> WS: Disable more broken patches

- patches/SLES-55380_8C913264.pnach
Causes crash on dark gaia phoenix.
> WS: Disable Sonic Unleashed WS

- patches/SLUS-20425_5D2C6E36.pnach
> WS: Disable SPSP ROTFD WS patch

- patches/SLES-50397_61F79C5A.pnach
- patches/SLES-50397_BAFCDA66.pnach
The patch was set to the wrong crc and that's why it was crashing. Now it works as it should.
> Prisoner of War fixed

- patches/SLUS-20184_24036809.pnach
- Door skip
- Source: https://gist.github.com/kapdap/91ff4e4a32d45b5a6ee6b9ef7b298895
- Skip startup logos
> Add patches for `SLUS-20184`

- patches/SLUS-21386_045D77E9.pnach
- patches/SLUS-21386_A616A6C2.pnach
- patches/SLUS-21386_B6B5A6DC.pnach
- patches/SLUS-21621_0033A2C2.pnach
This PR adds support for these Fan Translations
- Tales of the Abyss - Spanish Fan Translation by [Tales Translations](https://toa.tales-tra.com/).
WS
- Persona 3 FES - Spanish Fan Translation by [TraduSquare](https://tradusquare.es/proyectos/persona-3-fes/).
WS, 480p and Controllable Party Members
> Add patches for spanish fan translations

- patches/SLPM-62048_12266F36.pnach
> WS: Disable Battlegear 2 WS patch

- patches/SLUS-20946_399A49CA.pnach
I added the 60fps patch to Grand Theft Auto: San Andreas (SLUS-20946GH) / Ver 1.03 (CRC 399A49CA) that LilNizzy from RetroAchievements created
https://retroachievements.org/viewtopic.php?t=16674&c=192090#192090
> added the 60fps patch to GTA San Andreas 1.03 US

- patches/SLUS-21420_07E37616.pnach
Adds 60FPS hack by asasega (tested and it works flawless)
> 60FPS hack for Chicken Little: Ace in Action

- patches/SLUS-20397_767E383D.pnach
WS Patch breaks fog and blur.
Master:
PR:
> WS: DIsable Tenchu Wrath of Heaven WS

- patches/SLPS-25338_26D1C561.pnach
- patches/SLPS-25339_26D1C561.pnach
Fixed hanging up at loading some certain FMV in Armored Core Nexus.
> Fix hanging up at loading FMV for Armored Core Nexus

- patches/SCUS-97112_0AE679AF.pnach
- patches/SLUS-20292_9D57694E.pnach
- patches/SLUS-20742_25E1B231.pnach
- patches/SLUS-21132_0C5D220A.pnach
- patches/SLUS-21221_C0AC5781.pnach
- patches/SLUS-21445_4437F4B1.pnach
- patches/SLUS-21779_2BE55519.pnach
Tested all of them, they work and look good
> Some deinterlacing patches

- patches/SLPM-66660_9E8F0454.pnach
add Hokuto no Ken - Shinpan no Sousousei - Kengou Retsuden 北斗の拳 審判の双蒼星 拳豪列伝 (Japan) auto progressive scan video mode and 640x480p
> add Hokuto no Ken progressive scan video mode and 640x480p

- patches/SLPM-55008_721DEBE4.pnach
add Sengoku Basara X 640x480 pixels and No interleacing mode
> add Sengoku Basara X 640x480 pixels mode

- patches/SLES-52886_381F8A7B.pnach
- patches/SLUS-20944_024BF3B4.pnach
By mistake in my most recent merged pull I have used raw Power Rangers - Dino Thunder patches but here I bring the correct and tested ones
Testing patch
[https://youtu.be/PC8ZSiikusE](url)
> Correct and tested Power Rangers - Dino Thunder patches

- patches/SLPM-62055_64328775.pnach
remove patch for Bloody roar 3
fixes #439
> NI :remove patch for Bloody roar 3

- patches/SLES-55147_DC180A6B.pnach
- patches/SLES-55569_492CB73E.pnach
- patches/SLPM-55231_F66FAFB2.pnach
- patches/SLUS-21731_A8D83239.pnach
- patches/SLUS-21899_61A7E622.pnach
Silent Hill - Shattered Memories: Splitted the no noise hack from the Widescreen hack, "author=" parameter added, and added support for the no noise hack in European release
> Silent Hill: Shattered Memories Patches

- patches/SLUS-20772_08FFF00D.pnach
Sorry for deleting the recent pr, issues on my end :/
This only works for the NTSC-U version.
> SSX 3 Aspect Ratio Patches

- patches/SLES-50115_073D7FB5.pnach
- patches/SLPS-25028_F9D5C6A6.pnach
- patches/SLUS-20189_C1760287.pnach
> TXR0: Expand widescreen patch with split-screen

- patches/SLES-50330_021396FD.pnach
- patches/SLES-50330_581954FC.pnach
- patches/SLES-51061_26954C46.pnach
- patches/SLES-51061_C498A04F.pnach
- patches/SLES-51061_CFCB0D20.pnach
- patches/SLES-52541_A1B3F232.pnach
- patches/SLES-52541_B440A8FE.pnach
- patches/SLUS-20062_5E115FB6.pnach
- patches/SLUS-20552_20B19E49.pnach
- patches/SLUS-20552_248E6126.pnach
- patches/SLUS-20552_9E312BAF.pnach
All bugs fixed in GTA III, Vice City and San Andreas. I've been testing them for a couple of weeks and in the next few days I'll test them more thoroughly and check that I did the ports right.
- GTA III and Vice City: Ambulances and firefighters arrive at their destination
- San Andreas: Ambulances and firefighters arrive at their destination and when going at maximum speed there are no graphical errors
Fixes #457 
Fixes #454 
GTA III:
______________________
Vice City:
_______________________
San Andreas:
4:3 original without patch
> GTA WS: Fixed known bugs in widescreen

- patches/SLPS-25856_B05805B6.pnach
Lara Croft Tomb Raider - Anniversary (Japan) 60 FPS patch
tested and works fine
> Lara Croft Tomb Raider - Anniversary (Japan) 60 FPS

- patches/SLPS-25842_8409FD51.pnach
> WS: remove Tales of Destiny patch

- patches/SLUS-20408_394F402E.pnach
> WS: Disable Pitfall NTSC-U WS

- patches/SLUS-20210_E0DADD1A.pnach
add 18 Wheeler - American Pro Trucker (USA) widescreen 16:9
> add 18 Wheeler - American Pro Trucker (USA) SLUS-20210_E0DADD1A widescreen 16:9 

- patches/SLUS-20714_6B0F338D.pnach
This little patch slows down the insane sensitivity used in this game
> Red Ninja: End of Honor - Reduce Camera Sensitivity

- patches/SLES-51697_2326C5C8.pnach
- patches/SLES-51697_CE942B2A.pnach
- patches/SLUS-20772_08FFF00D.pnach
Patches for the NTSC, PAL 1.0 and PAL 2.0 Copies
> SSX 3 Metro Slowdown Fix and No Intro

- patches/SLES-50325_53DF159B.pnach
- patches/SLES-50325_E7FB0320.pnach
- patches/SLES-50326_52E0597D.pnach
- patches/SLES-50326_C669B63C.pnach
- patches/SLES-51954_564F352C.pnach
- patches/SLES-52020_9771C478.pnach
- patches/SLES-52149_80FAC91D.pnach
- patches/SLES-52149_990E57D1.pnach
- patches/SLES-52149_AB82114E.pnach
- patches/SLES-52337_D03BEE2A.pnach
- patches/SLES-52338_D03BE12A.pnach
- patches/SLES-52725_CFB873AD.pnach
- patches/SLES-52872_715AD5FD.pnach
- patches/SLES-53287_4C4D7873.pnach
- patches/SLES-53287_A1C2614A.pnach
- patches/SLES-53287_DDAEB7A6.pnach
- patches/SLES-53552_686B786E.pnach
- patches/SLES-53557_692CBA8E.pnach
- patches/SLES-54323_4078F8F1.pnach
- patches/SLES-54324_26DFEE66.pnach
- patches/SLES-54402_2BB7BA40.pnach
- patches/SLES-54478_D76BF975.pnach
- patches/SLES-54492_C2909885.pnach
- patches/SLES-54834_6D1B0C02.pnach
- patches/SLES-55109_D5D1D002.pnach
- patches/SLES-55294_5EEFD8C0.pnach
- patches/SLES-55351_422281E6.pnach
- patches/SLUS-21267_270F8C03.pnach
- patches/SLUS-21493_7841A89E.pnach
- Various patch updates
- Quality of life improvements
- Fixed some CRCs to work correctly
Everything is tested and working. I've even completed almost the entire game for several.
> Patches: Several updates

- patches/SLUS-21422_433B0342.pnach
- patches/SLUS-21422_75A5436A.pnach
**Tom Clancy's Ghost Recon - Advanced Warfighter NTSC-U SLUS-21422 75A5436A**
- Widescreen 16:9 (Tested :heavy_check_mark:)
Patch tested and working in all game modes :heavy_check_mark:
> WS support for Ghost Recon - Advanced Warfighter

- patches/SLES-52276_83BE7C8E.pnach
- patches/SLUS-21116_FD2CF599.pnach
**187 - Ride or Die PAL-M SLES-52276 83BE7C8E**
- 50/60 FPS (Tested :heavy_check_mark:)
**187 - Ride or Die NTSC-U SLUS-21116 FD2CF599**
- 60 FPS (Tested :heavy_check_mark:)
> 50/60 FPS patches for 187 - Ride or Die

- patches/SLES-54587_8DD6DDA3.pnach
- patches/SLES-54587_A98B5AD6.pnach
- patches/SLES-54587_A98B5B22.pnach
**Raw Danger  (Regular version)**
- Updated gametitle
- Add Remove Colorgrading Filter patch
**Raw Danger  (Undub & NTSC Mode versions)**
- Updated gametitle (Undub & NTSC Mode shares the same CRC)
- Add Remove Colorgrading Filter patch
**Raw Danger  (NTSC Mode + Performance version)**
- Updated gametitle
- (Unnecessary to add Remove Colorgrading Filter patch here, since romhack already includes it.)
Some screenshots before and after with the Remove colorgrading filter patch
> Raw Danger (PAL) - Updates

- patches/SLUS-20946_19A84291.pnach
This game version is a dummy patch for a "Viva Las Vegas" RetroAchievements subset:
<https://retroachievements.org/game/22085>
> GTA San Andreas: Copy US v1.03 patches for a RetroAchievements subset

- patches/SLES-52822_105CC366.pnach
- patches/SLUS-20509_F9DCF583.pnach
These patches truly are breaking new ground.
> Disable more broken WS patches

- patches/SLUS-20974_D7273511.pnach
Fix patch so people can use widescreen patch (also in hardcore retroachievements)
> ws: Digital Devil Saga

- patches/SLES-50649_DF96CC28.pnach
- patches/SLUS-20236_689339AC.pnach
Changes:
- This fix prevents the tutorial books from being deformed and squashed.
All of the patches have been tested for all versions of the games, and relevant comments have been added.
> Patches: Taz Wanted Minor Fix

- patches/SLUS-20240_7DBA914D.pnach
removes broken  WS patch fixes https://github.com/PCSX2/pcsx2/issues/13092
> WS:remove broken patch for Conflict Zone - Modern War Strategy
