cheats_ws/0CFFFBCC.pnach

Appears to break both software and hardware rendering.
Screenshots from RedDevilus

WS: Comment out Baroque WS patch

---

cheats_ws/27E54B37.pnach
cheats_ws/3676E74C.pnach
cheats_ws/D5605611.pnach

The game in question is "Syphon Filter: the Omega Strain"
it has 3 versions:
-USA (NTSC-U)
-Europe/Australia (PAL)
-Korea (NTSC-K)
So that makes them 3 widescreen pnachs, they are all included in the cheats_ws.zip of PCSX2 1.6 and 1.7 the nightly build, but they are faulty, i did the right adjustments and i want the correct form of the pnachs to be included inside cheats_ws.zip in future updates (at least the regular nightly builld updates).
The widescreen patch for each version is 3 fold, Gameplay, Hud, & FMV.
The gameplay and FMV worked correctly already, but the HUD elements like radar and weapon icon are not on the edges of the screen, they are actually 4:3 and are placed in the center of the screen when the HUD patch is active, while eveything else is in 16:9 widescreen, so the …

WS:Syphon Filter: The Omega Strain Fixed HUD

---

cheats_ws/F880239B.pnach

Causes the car to disconnect from the model and make the game unplayable.

WS: Disable Tokyo Road Race patch

---

cheats_ws/9DD290E2.pnach

Causes the crowd and signs to float in the air and move with the camera.

WS: Disable Sega Soccer Slam patch

---

cheats_ws/59319476.pnach

Patch breaks radar rendering causing it to be offset.
Issue link:
https://forums.pcsx2.net/Thread-Mobile-Suit-Gundam-Federation-vs-Zeon-Radar-and-Lock-On-Issues-on-nightly-build

WS: Disable patches for Mobile Suit Gundam Federation vs. Zeon

---

cheats_ws/AA294EDC.pnach

This patch force-enables native widescreen in the NTSC version of Colin McRae Rally 3. The PAL version had it available in Graphics options, it's later been removed in the NTSC release for performance reasons (due to higher FOV).
Also posted here: https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=631400#pid631400

WS: Colin McRae Rally 3 (SLUS-20502)

---

cheats_ws/C5473413.pnach

Commenting out the whole patch as saving/loading font is invisible along with zooming problems seemingly.
see:
https://github.com/PCSX2/pcsx2/pull/7988#issuecomment-1407520072

WS: Harry Potter and the Chamber of Secrets

---

cheats_ni/588CC41B.pnach

Original patch also nopped a function that applied a film grain/noise effect to the game. This is correctly emulated and doesn't need to be removed.

NI: Update Breath of Fire V (USA) patch

---

cheats_ws/BAFCDA66.pnach

Caused the emulator to crash on boot up.

WS: Disable Prisoner of War patches.

---

cheats_ws/812C5A96.pnach

This is a fix for Onimusha Dawn of Dreams 812C5A96.pnach
The old one was broken and it only showed 2d elements, no 3d graphics.

WS: Fix for Onimusha Dawn of Dreams Pal version pnach

---

cheats_ws/32A1C752.pnach
cheats_ws/44A61C8F.pnach
cheats_ws/77E61C8A.pnach

Fixes the text aspect ratio of Gran Turismo 4 for widescreen. This feature was originally exclusive to _Gran Turismo 4 Online Public Beta_, but has been ported to the retail version of the game.
- Gran Turismo 4 [SCUS-97328] (U)
- Gran Turismo 4 [SCES-51719] (E)
- Gran Turismo 4 Online Public Beta [SCUS-97436] (U)

WS: Add Gran Turismo 4 (NTSC-U) (PAL) patches

---

cheats_ws/1A7A27E6.pnach
cheats_ws/72A924F1.pnach
cheats_ws/82C46B7A.pnach
cheats_ws/91ECC411.pnach
cheats_ws/B1F87437.pnach
cheats_ws/CC8451F9.pnach
cheats_ws/E7EA3288.pnach

Adds SpongeBob CFTKK 16:9 patches, Pac-Man World 3 and one Pac-Man World 2 patch that enables the unused official widescreen mode in the NTSC-U Greatest Hits version not implemented in the options menu until the later PAL and NTSC-J releases.

Add more Blitz 16:9 patches

---

cheats_ni/047D8AA6.pnach
cheats_ni/049BF05D.pnach
cheats_ni/5EA6B8BE.pnach
cheats_ni/916B1D2E.pnach
cheats_ni/E7EA3288.pnach

Adds no-interlacing patches for the NTSC (USA and Japan) versions of Pac-Man World 2 and Dead to Rights.

Add Pac-Man World 2 & Dead to Rights No-Interlacing patches

---

cheats_ws/45FE0CC4.pnach
cheats_ws/B3A71D10.pnach

Adds 16:9 patch for the Greatest Hits version of Going Commando, and re-adds Up Your Arsenal 16:9 patch with an updated fixed version. Previously the UYA 16:9 code caused the boss in the first vid-comic level to break, but the author uploaded a fixed version, so there shouldn't be issues with it anymore afaik.

Add more NTSC-U Ratchet 16:9 patches

---

patches/SLUS-21191_AA525269.pnach

This PR Fixes the broken WS patch as was shown on #60.
Also properly fixes the formatting in accordance to the new syntax format.
~~Putting as draft for now, while waiting for a member to test the patch in few hours.~~
The patches now shows up properly on the patch tab:

Patches: Fix Tag Team Racing WS and tidy up formatting

---

patches/SLUS-21328_99BD2C0C.pnach
patches/SLUS-21583_C6E85EF0.pnach
patches/SLUS-21661_8FCCB5D9.pnach
patches/SLUS-21728_6A8448BA.pnach
patches/SLUS-21815_DB2DE310.pnach
patches/SLUS-21921_8A1D18EE.pnach

This PR adds 60 FPS patches to several  games namely:
- Crash of The Titans (SLUS-21583)
- Crash - Mind Over Mutant (SLUS-21728)
- Pac-Man World Rally (SLUS-21328)
These are tested personally by me, from beginning to end game with no game breaking glitches in sight.
Also fixed the formatting for some games.

Patches: Add 60 FPS to Crash Bandicoot games and Pac-Man World Rally

---

patches/SLPS-25007_F3F906DE.pnach
patches/SLPS-25040_5F2A0E36.pnach
patches/SLPS-25112_D00E1931.pnach
patches/SLPS-25169_124C0F8D.pnach
patches/SLPS-25339_26D1C561.pnach
patches/SLPS-25408_5C4E1AC4.pnach
patches/SLPS-25461_3E26EEEB.pnach
patches/SLPS-25462_FEBE1992.pnach
patches/SLUS-20249_9545216B.pnach
patches/SLUS-20435_FDB4D261.pnach
patches/SLUS-20644_B8BFF0B1.pnach
patches/SLUS-21200_72486978.pnach

Add missing Armored Core NI patches for the following games:
(US) Armored Core 2 Another Age
(US) Armored Core 3
(US) Armored Core 3 Silent Line
(US) Armored Core Nine Breaker
(JP) All Armored Core Games

Patches: Add missing Armored Core US/JP NI Patches

---

patches/SCUS-97353_49536F3F.pnach
patches/SLES-82031_167A484D.pnach
patches/SLES-82037_F3A5EC6F.pnach
patches/SLES-82039_812C5A96.pnach
patches/SLKA-25202_1102F889.pnach
patches/SLPM-65977_5B659BED.pnach
patches/SLPM-66276_BD17248E.pnach
patches/SLPS-73215_F7671511.pnach
patches/SLUS-21044_F3BDB2E6.pnach
patches/SLUS-21079_7E5F690C.pnach
patches/SLUS-21133_BBBAAF63.pnach
patches/SLUS-21133_EB39ABEC.pnach
patches/SLUS-21345_5B657DAD.pnach
patches/SLUS-21362_FE44479E.pnach
patches/SLUS-21417_2088950A.pnach

If any of these are incorrect, they can be manually removed later.
We know Growlanser and MGS3 have different ELFs, at least, so I ignored those.
Closes #93.

Copy multi-disc patches with same CRC to second disc

---

patches/SLES-50992_5B9ACF79.pnach
patches/SLES-51107_5B9ACF79.pnach
patches/SLES-51108_5B9ACF79.pnach
patches/SLES-51109_5B9ACF79.pnach
patches/SLES-51110_5B9ACF79.pnach
patches/SLES-53028_13E1AD6A.pnach
patches/SLES-53029_72DC82B5.pnach
patches/SLES-53031_72DC82B5.pnach
patches/SLES-53032_72DC82B5.pnach

Adds missing patches for variations of Blood Money and Silent Assassin.
Fixes #92

Correct Hitman 2 - Silent Assassin + Blood Money patches

---

patches/SLES-53820_B1A38C05.pnach
patches/SLES-82037_F3A5EC6F.pnach
patches/SLKA-25202_1102F889.pnach
patches/SLPS-25338_26D1C561.pnach
patches/SLPS-25339_26D1C561.pnach
patches/SLPS-25408_5C4E1AC4.pnach
patches/SLPS-25461_3E26EEEB.pnach
patches/SLPS-25462_FEBE1992.pnach
patches/SLUS-20986_7E5F690C.pnach
patches/SLUS-21079_7E5F690C.pnach
patches/SLUS-21200_72486978.pnach
patches/SLUS-21338_1F34E107.pnach

Changes:
- Added `[No-Interlacing]` patch for `SLES-53820_B1A38C05.pnach`
- Added `[Remove Blur]` and `[Correct HUD]` patches for some Armored Core games.
- Fixed gametitle for Armored Core Nexus games.

Add visual patches for Armored Core games

---

patches/SLUS-20224_047D8AA6.pnach

This PR adds in widescreen patches which are taken from `Pac-Man World 2 (Greatest Hits)` (https://github.com/PCSX2/pcsx2_patches/blob/main/patches/SLUS-20224_E7EA3288.pnach#L7) as the patch seems to also works fine on the base game, tested several levels and no graphical issues so far.

Add widescreen patches to Pac-Man World 2

---

patches/SLES-53820_B1A38C05.pnach
patches/SLPS-25338_26D1C561.pnach
patches/SLPS-25339_26D1C561.pnach
patches/SLPS-25462_FEBE1992.pnach
patches/SLUS-20986_7E5F690C.pnach
patches/SLUS-21079_7E5F690C.pnach
patches/SLUS-21338_1F34E107.pnach

Changes:
- Fixed `Remove Blur` patch doesn't work in some missions. (Armored Core - Nexus)
- Fixed `Remove Blur` patch messes up screen without NI patch. (Armored Core - Last Raven)

Fix some Armored Core patches

---

patches/SLES-52159_51AB1AB0.pnach

Fixes offset elements like locked screen in Grand Prix
With WS patch:
Without it:

WS: Myth Makers Super Cart GP

---

patches/SLES-53439_E2FF6D3D.pnach

This PR Fixes the broken WS patch as was shown on https://github.com/PCSX2/pcsx2_patches/issues/60 but for PAL version.
Also properly fixes the formatting in accordance to the new syntax format.

Patches: Fix CTTR (PAL) WS and tidy up formatting

---

patches/SLES-52541_A1B3F232.pnach
patches/SLES-52541_B440A8FE.pnach
patches/SLPM-55292_9E18263C.pnach
patches/SLPM-65984_60FE139C.pnach
patches/SLUS-20946_2C6BE434.pnach
patches/SLUS-20946_399A49CA.pnach

Original patches caused TLB misses constantly, breaking the game, this should resolve that.

Update GTA SA Radiosity patches to not cause TLB misses

---

patches/SLES-52541_A1B3F232.pnach
patches/SLES-52541_B440A8FE.pnach
patches/SLPM-55292_9E18263C.pnach
patches/SLPM-65984_60FE139C.pnach
patches/SLUS-20946_2C6BE434.pnach
patches/SLUS-20946_399A49CA.pnach

Redid the patches to nop out the actual function that does the radiosity instead of random bits of memory, it was getting a bit silly modifying pointers and it could break at any time.
This actually nops the function out, the memory search i used for the two instructions before the jump you need to nop was 27a5010c0040202d

Redo GTA SA Radiosity patches

---

patches/SLPM-67546_6898435D.pnach

Patch author obviously forgot to change the serial, so when we used a script to update all the names, it failed here.
Fixes #131

Correct serial for LOTR Two Towers patch

---

patches/SLES-50330_021396FD.pnach
patches/SLES-50330_581954FC.pnach
patches/SLES-50487_5E641834.pnach
patches/SLES-51061_26954C46.pnach
patches/SLES-51061_C498A04F.pnach
patches/SLES-51061_CFCB0D20.pnach
patches/SLES-52256_D13BEF2C.pnach
patches/SLES-52541_A1B3F232.pnach
patches/SLES-52541_B440A8FE.pnach
patches/SLES-53439_E2FF6D3D.pnach
patches/SLES-54126_E393DFE5.pnach
patches/SLES-54135_D693D4CF.pnach
patches/SLES-54182_301A1B6E.pnach
patches/SLES-54400_B1F87437.pnach
patches/SLES-54622_B3AD1EA4.pnach
patches/SLES-54841_ECA6BFC5.pnach
patches/SLES-55024_AE28C9C7.pnach
patches/SLES-55204_0F89A154.pnach
patches/SLUS-20352_614F7928.pnach
patches/SLUS-20814_CD68E44A.pnach
patches/SLUS-21111_41F4A178.pnach
patches/SLUS-21391_82C46B7A.pnach
patches/SLUS-21644_1FF9C051.pnach

Changes:
- Add 50/60 FPS patches to Family Guy
- Add Widescreen (PAL) patch to Family Guy (Ported from NTSC-U version)
- Add missing Widescreen, No-interlacing and 50 FPS patches to all (PAL) versions of the GTA Trilogy
- Add 50/60 FPS patches to Looney Tunes Space Race
- Add 50/60 FPS patches to Max Payne 2
- Add 50/60 FPS patches to Scarface
- Add 50/60 FPS patches to SpongeBob Creature from the Krusty Krab
- Add 50/60 FPS patches to SpongeBob's Atlantis SquarePantis
- Various corrections and tidy up formatting
All of the patches have been tested for all versions of the games, and relevant comments such as activating widescreen in-game or the need for EE Overclock have been added.

Patches: Various additions and corrections

---

patches/SLES-51794_26F6F521.pnach
patches/SLES-52372_6B68932C.pnach
patches/SLES-54359_0EE5646B.pnach
patches/SLES-54815_8AE9536D.pnach
patches/SLUS-20853_0BB7AE9B.pnach
patches/SLUS-21372_D03D4C77.pnach
patches/SLUS-21607_B80CE8EC.pnach

Changes:
- Add 50/60 FPS patches to The Legend of Spyro A New Beginning
- Add 50/60 FPS patches to The Legend of Spyro The Eternal Night
- Add 50/60 FPS patches to Looney Tunes Back in Action
- Add Widescreen patches to Looney Tunes Back in Action
- Improve Spider-Man 2 (NTSC-U) Widescreen patch (Fixed Spider-Man's shadow, fixed the missing map/compass, added more HUD components, commented some problematic HUD addresses)
- Add Widescreen patch to Spider-Man 2 (PAL): Equivalent to NTSC-U.
- Improve Spider-Man 2 (NTSC-U) 60 FPS patch (Fixed FMVs playing accelerated)
- Add 50 FPS patch to Spider-Man 2 (PAL): Equivalent to NTSC-U.
All of the patches have been tested for all versions of the games, and relevant comments such as activating widescreen in-game or the need for EE Overclock have …

Patches: Various additions and improvements

---

patches/SCUS-97621_3DC2FE45.pnach

The repo was using an outdated version of this game's widescreen hacks (v3):
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=571823#pid571823
This updates the hacks to the latest version (v4):
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=606368#pid606368
Reported by DoofusMan:
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=635558#pid635558

Patches: Update Twisted Metal Head-On widescreen hacks to v4

---

patches/SLES-50539_992B46DC.pnach
patches/SLPM-67505_60666E72.pnach
patches/SLUS-20265_79646C72.pnach

This PR improves the current widescreen patch for 007: Agent Under Fire. The following improvements are now in:
1. Moved to a new naming scheme with an explicitly stated author.
2. Fixed the patch stomping on memory outside of the on-foot segments by making it apply conditionally. The patch was "lucky" that during the driving segments it stomped on some meaningless debug strings. Unfortunately, the game does not switch ELFs via BIOS, so it is not possible to split patches by CRC, and instead "if checks" need to be used.
3. Added a patch for the driving segments of the game that are handled by a separate ELF file.
4. Added support for the PAL version, all languages.
Drafted until I've discussed it with the dev of AUF Reloaded, since apparently there were past efforts in fixing the driving …

Patches: Better widescreen fixes for 007: Agent Under Fire

---

patches/SLUS-20362_1D2818AF.pnach

The previous one is for PAL version and doesn't work for both regions as claimed.
Old "fix"
Proper fix

Patches: Correct NFS HP2 NTSC-U ws fix

---

patches/SLES-53191_F7780E06.pnach
patches/SLES-53900_C7993BCC.pnach
patches/SLPM-65246_0AD22FB5.pnach
patches/SLPM-65246_2046216F.pnach
patches/SLPM-65514_C37C1B76.pnach

Adds no interlacing patches for the following games:
[EU] Kaido Racer
[EU] Kaido Racer 2
[JP] Kaido Battle
[JP] Kaido Battle 2 Chain Reaction
[JP] Kaido Touge no Densetsu
Added an additional patch for Kaido Battle 1 JP, since the original CRC doesn't match mine and I can't find anything about the original CRC.

NI: Add NI patches for Kaido Battle games (JP&EU)

---

patches/SLES-50920_401F4726.pnach
patches/SLPS-25057_04C3765E.pnach
patches/SLUS-20318_36E02E91.pnach

Removes scanmask usage from the game, which doesn't seem to do much but make things blurrier when turning.
It still looks a bit blurry to me when actually in motion, but as you can see below from the stills taken when turning, it's clearer.
Normal:
Patched:

Add scanmsk removal patch

---

patches/SLUS-20733_28270F7D.pnach

Patch does not AR adjust item icons in buy menus. Might be a good idea to disable until someone can work out how to fix it.

Patches: Disable Castlevania: Lament of Innocence Widescreen Patch

---

patches/SLES-50071_831078BD.pnach
patches/SLES-50731_1D2818AF.pnach
patches/SLES-51054_ACB1989A.pnach
patches/SLES-51191_692C87AD.pnach
patches/SLES-51967_FDA10318.pnach
patches/SLES-52188_F59FF56B.pnach
patches/SLES-52478_E2E67E23.pnach
patches/SLES-52725_CFB873AD.pnach
patches/SLES-52942_EBE1972D.pnach
patches/SLES-53147_F67E4351.pnach
patches/SLES-53559_CA2A1B04.pnach
patches/SLES-54007_B8435BF4.pnach
patches/SLES-54235_C398F477.pnach
patches/SLES-54323_4078F8F1.pnach
patches/SLUS-20063_DFD26C76.pnach

NFS Series: Added 60 fps patches that maintain the original resolution and speed.
Midnight club series: found native address that regulates the aspect ratio for 16:9, no rendering hacks needed.
Kingdom hearts 2: finished game from start to finish and optimized the code.
The rest of the 60 fps patches also maintain the original speed

Update widescreens patches and 60fps

---

patches/SLUS-21050_BEBF8793.pnach

Also added Aero_ as the widescreen fix author at the beginning.

Patches for Burnout 3 (60 FPS menus & crashes, always ask for 480p output, MPH to KPH)

---

patches/SLUS-20238_103B5706.pnach

This PR adds several upscaling fix patches for crash wrath of cortex.
Credit to TechieSaru.

Add several upscaling fixes for Crash WOC

---

patches/SLUS-21372_D03D4C77.pnach

A quick fix to the 60 FPS patch for The Legend of Spyro A New Beginning (NTSC-U) that caused FMVs to play accelerated. I tested it and now it works as it should.

Patches: Fix 60 FPS patch to The Legend of Spyro A New Beginning

---

patches/SLUS-20909_8CFAB4EA.pnach
patches/SLUS-20909_B318AA3C.pnach

A patch for Crash Twinsanity that enables the widescreen flag at all times (B318AA3C, 8CFAB4EA). Cheats by TechieSaru!

Crash Twinsanity Widescreen Patch (SLUS-20909)

---

patches/SLPS-25217_38145680.pnach

Patch to remove scanmask usage from Shadow Tower Abyss. Same issue as #200 , patch is based off that one.
https://github.com/PCSX2/pcsx2_patches/assets/53349573/bed7e6ef-6dfc-496b-8321-b138a3767c2a

Patches: Shadow Tower Abyss - Remove Scanmask Blur

---

patches/SLUS-20315_4B8E0DE8

Sets, on boot the default screen mode for Spyro: Enter the Dragonfly to be set widescreen instead of standard.

Add Spyro default TV mode (SLUS 20315)

---

patches/SLES-51043_0EF1D4BA.pnach
patches/SLUS-20315_4B8E0DE8
patches/SLUS-20315_4B8E0DE8.pnach

Changes:
- Improvements to the NTSC-U patch.
- Add patch to PAL version of the game.
All of the patches have been tested for all versions of the games, and relevant comments such as activating widescreen in-game or the need for EE Overclock have been added.

Patches: Spyro Enter the Dragonfly widescreen patch

---

patches/SLUS-20909_8CFAB4EA.pnach
patches/SLUS-20909_B318AA3C.pnach

I am re-submitting my (TechieSaru's) patches that I strongly believe were replaced with malicious intent for the following three reasons:
The uploader mentioned that their update was a "fix" and delibrately chose not to specify what it was "fixing"
BOTH patches were replaced
I was never directly informed that there was an issue with my patch
The patch I originally created was by request for a friend (Reverie). It was for v2.00 of crash twinsanity and my friend and myself verified that it worked fine.
Upon futher investigation, I figured out that the "fix" that the uploader was, again, being deceitful about, is due to my friend making an erroneus assumption that my hack worked for both versions of Twinsanity.
I have taken the opportunity to correct this error with my patch.

Restore unjustly removed twinsanity widescreen patches

---

patches/SLES-52568_1510E1D1.pnach
patches/SLPM-65801_0CA02D02.pnach
patches/SLUS-20909_8CFAB4EA.pnach
patches/SLUS-20909_B318AA3C.pnach

The (NTSC-U) patches are now officially fundamentally broken.
The 1.0 version of the game greets you with this mess (and if you continue the game crashes):
And this is what it should look like (And what it looks like with my patch):
And 2.0 version doesn't even go past a black screen.
And after a quick check, one of the lines in my patches wasn't necessary, so now there's no more writing to dynamically allocated memory, and therefore my patches only include a single line, that's why I'm updating not only the broken patches but all four of them.

Patches: Fix Crash Twinsanity widescreen patches again

---

patches/SLES-54842_B4B4E877.pnach
patches/SLES-54843_AEFD7D25.pnach
patches/SLES-55205_0F89A154.pnach
patches/SLES-55206_0F89A154.pnach

Changes:
- Add missing patches to Russian and Scandinavian versions of Crash of the Titans.
- Add missing patches to Russian and Scandinavian versions of Crash Mind Over Mutant.
- Changed the EE Overclock recommendation to Crash of the Titans.
All of the patches have been tested for all versions of the games, and relevant comments such as activating widescreen in-game or the need for EE Overclock have been added.

Patches: Crash of the Titans and Crash Mind Over Mutant missing versions

---

patches/SLPS-25338_26D1C561.pnach
patches/SLPS-25339_26D1C561.pnach
patches/SLPS-25408_5C4E1AC4.pnach
patches/SLPS-25461_3E26EEEB.pnach
patches/SLUS-20986_7E5F690C.pnach
patches/SLUS-21079_7E5F690C.pnach
patches/SLUS-21200_72486978.pnach

Overhauled Widescreen patches and No-interlace patches of these games:
- Armored Core - Nexus
- Armored Core - Nine Breaker
- Armored Core - Formula Front
Note: Only for NTSC-J and NTSC-U.

Maintain patches for Armored Core games

---

patches/SLES-53819_98BE10F8.pnach
patches/SLES-82036_F3A5EC6F.pnach
patches/SLES-82037_F3A5EC6F.pnach

For below two PAL games, rewrote Widescreen patch and added No-Interlacing patch, Blur Removal patch, and Fixing HUD patch.
- Armored Core Nexus (Disc 1 and 2)
- Armored Core Nine Breaker
Note:
- I used Blockdumps and SaveStates coming from another user for writing & testing patches.
- As far as I tested, all patches work on both frame rate modes (50Hz and 60Hz).

Add various patches for PAL Armored Core games

---

patches/SLES-50821_22E91837.pnach

this patch used to be mixed with [No interlacing]
so I decided to separate these patches, as one of them is an attempt against the atmosphere of the game.
now the user will be able to disable/enable as desired
without patch
with patch

Project Zero - Remove Post Processing patch update

---

patches/SLES-51054_ACB1989A.pnach
patches/SLES-52942_EBE1972D.pnach
patches/SLUS-20209_E5F2DF38.pnach
patches/SLUS-21029_0DD3417A.pnach

Based on the 4:3 ratio, I have corrected it and would say it is accurate. With the previous value it is a little narrower. I attached images

Midnight club 2 and 3 widescreen correction

---

patches/SLES-51950_B7CF071A.pnach
patches/SLES-53350_4A198252.pnach
patches/SLES-55380_8C913264.pnach

Sonic Heroes: You can choose between 50 and 60hz without altering anything in the game if 50hz is selected by mistake, this way it is more faithful. Selecting 60 Hz automatically switches to progressive mode
Sonic Unleashed: Fixed aspect ratio as shown in the images.
What I have marked with a red arrow is from the panoramic patch, when enabled it cannot be hidden because it is part of the map. I haven't been able to fix it but it doesn't affect the gameplay.
Update: In the end I found the direction of widescreen, it does not require a rendering fix and works very well, plus the HUD looks better this way without showing that part of the map that I marked in red.
__________________________________________________________________________________________________________________________________ …

Update 60 fps: Sonic heroes and unleashed

---

patches/SCES-50240_68707E85.pnach
patches/SCUS-97112_0AE679AF.pnach
patches/SLES-50672_4A9D8E01.pnach
patches/SLES-51433_CDD0C904.pnach
patches/SLES-53039_5C64E73A.pnach
patches/SLUS-20035_773A8DAB.pnach
patches/SLUS-20675_B0859096.pnach
patches/SLUS-20973_4028A55F.pnach

With the new revisions, pcsx2 does an excellent job with interlacing and there are really very few games that require this.
As seen in the images, the interlacing patch prevents the letters from displaying correctly and the sawtooth becomes more noticeable in the graphics, even if we increase the resolution.
On the left side interlaced patch enabled and on the right interlaced patch disabled
Baldur's Gate - Dark Alliance
Baldur's Gate - Dark Alliance 2
Champions - Return to Arms
Extermination
Ghost Vibration

Remove no-interlaced patches

---

SLUS-20831_0F932D81.pnach
patches/SLUS-20831_0F932D81.pnach

There are two Wanderers in Tokyo Xtreme Racer 3 that is unreachable in the American release.  The localization team left these at the Japanese values of 100 million (for Whirlwind Fanfare), and 20 million (For Exotic Butterfly).  They changed the starting cash from 4 million credits to 40 thousand credits.   
This is a fix that reduces the requirements for those two Wanderers to 1 million credits and 200 thousand credits (Which is the reduction by a factor of 100 that all other credit values changed).  
This will make it so Whirlwind Fanfare is reachable for the first time in 20 years with out a cheat device, and make players be able to reach Exotic Butterfly correctly. 
Let me know if there are any issues.

SLUS-20831 TXR3 Wanderers fix

---

patches/SLUS-20927_E0D4421A.pnach

This removes the flash/fog effect when firing weapons in Time Crisis: Crisis Zone using the Guncon. 
Before:
https://cdn.discordapp.com/attachments/453242743292952578/1190917518408290324/2023-12-31_02-20-04.mp4?ex=65a38b5e&is=6591165e&hm=a0f5596a37ddb029fd20cbf27f3aefddc0e136a22769adce83c0dcb77ce55ba1&
After:
https://cdn.discordapp.com/attachments/1185062307571695636/1190948508941946890/2023-12-31_04-16-22.mp4?ex=65a3a83b&is=6591333b&hm=3d49fbc979f9869afb73721236a874989a7a7d4a34d8178208bd413334d11e35&
Wasn't particularly sure of the exact syntax/meaning (for comments and the text in brackets and such) so let me know if anything needs to be changed.

Add guncon flash removal patch for Time Crisis: Crisis Zone

---

patches/SCKA-20109_8897C208.pnach

These were added without using the comment syntax, which causes these lines to get ignored when processing the patch. Fixes these so the lines will work as expected.
Further down they correctly used `//#1`, implying it was their intention to have this as a note/comment.

Fix broken comments - syntax error

---

patches/SLES-50044_55EDA5A0.pnach
patches/SLES-50069_FD8F4257.pnach
patches/SLES-50074_4A805DF1.pnach
patches/SLES-50955_0CEB8F2F.pnach
patches/SLES-51821_83466553.pnach
patches/SLES-52247_36ECD588.pnach
patches/SLES-52729_59A5C81C.pnach
patches/SLES-52857_38351989.pnach
patches/SLES-53575_82CA3505.pnach
patches/SLES-53654_2E66AAEA.pnach
patches/SLES-54343_A90A973D.pnach
patches/SLES-54473_8B0725D5.pnach
patches/SLES-54527_4CB5D96E.pnach
patches/SLES-54952_1712E9F9.pnach
patches/SLES-54989_FD4FE026.pnach
patches/SLES-55016_9D6AA1B8.pnach
patches/SLES-55357_26847412.pnach
patches/SLES-55374_76B70CCE.pnach
patches/SLES-55486_084CC895.pnach
patches/SLES-55592_35C84D80.pnach
patches/SLES-55625_5ED15549.pnach
patches/SLPM-67519_D2F77DF2.pnach
patches/SLUS-20138_D2F77DF2.pnach
patches/SLUS-21015_09052A4D.pnach
patches/SLUS-21622_07717046.pnach
patches/SLUS-21870_D3C84C28.pnach

The patches are tested and work correctly.
Changes in Rayman 2 - Revolution. The previous patch maintains 50fps at all times and makes some scenes play twice as fast. Some examples of these scenes:
Previous patch running at double speed
New patch fixed
It works the same in ntsc-u version, in gameplay it changes automatically

Adding widescreen and fps patches

---

patches/SLES-53561_C78A495D.pnach
patches/SLPS-25879_019CFA48.pnach
patches/SLUS-21269_28703748.pnach

Adds depth of field removal to Bully games.
It doesn't upscale well, and users hate it, so now they can turn it off.

Add Disable Depth of Field patch to Bully/Canis Canem

---

patches/SCKA-20109_8897C208.pnach
patches/SLUS-20216_79B8A95F.pnach

Removes forced 480p 60 fps mode that causes double speed and party control mod that was not in it's own section.

Patches: Clean up Persona 3 FES NTSC-K patch

---

patches/SLUS-21419_44A5FA15.pnach

Causes black spheres or other colour of sphere to appear in the sky or in some corridors at certain viewing angles.

Patches: Disable FF7 DOC WS patch

---

patches/SLUS-20766_1C6C1DB6.pnach

Added support for the undub version by wagrenier (https://github.com/wagrenier/Zero2Undub)
Also 2 lines of text were updated in these patches (Standar version&Undub version)
Undub version before
Undub version after

WS: Fatal Frame 2

---

patches/SLPS-25338_26D1C561.pnach
patches/SLPS-25339_26D1C561.pnach
patches/SLPS-25408_5C4E1AC4.pnach

- Partially reverted `[No-Interlacing]` patch for Armored Core Nexus (both NTSC-J discs).
- My apologies. This patch has been broken since my last PR.
- Rewrote conditional lines of `[Remove Blur]` patch for Armored Core Nexus (both NTSC-J discs) and Armored Core Nine Breaker (NTSC-J).

Fix No-Interlacing patch for Armored Core Nexus

---

patches/SCES-50001_0DD8941C.pnach
patches/SCES-50878_F48F994A.pnach

Add interlacing patches
Tekken Tag: tested all game modes, fmv and scenes
before
after
Tekken 4: In this pull this interlacing patch is removed because when an fmv was released it changed to PAL. Talking to a friend who works fine for him, I realized that my old save game was corrupted. I deleted the save and completed it again without fmv problem.
https://github.com/PCSX2/pcsx2_patches/pull/247/files#diff-17960fdef464f7674073fab4ba8bfc849df27f2a293dc0cb427c052c6ba2c61e

No-Interlacing: Tekken 4 and Tekken tag tournament PAL

---

patches/SLUS-21355_60A42FF5.pnach

Added SuperType1's HUD fix to Midnight Club 3 Remix. The fix is not perfect, with it not supporting Software rendering and a minor lighting cutoff bug. Still, makes playing in widescreen much more tolerable.

Added MC3R HUD fix

---

patches/SLUS-21419_44A5FA15.pnach

Older patch have render issues as refraction exposed at issues section, I made a new patch that fix that missing of render and correctly scaling, so no more black hole at the sky
Fixes #295

New WS patch for Dirge of Cerberus - Final Fantasy VII

---

patches/SLES-53124_821A0C40.pnach
patches/SLES-53124_CD9DAA4C.pnach
patches/SLES-53124_F00CA82B.pnach

This game runs 3 .elf and with the new pnach system it does not work correctly. It does not require conditionals because the widescreen addresses change every time an .elf is executed and there is no conflict. The only thing I haven't been able to test is LAN/Internet Multiplayer because I don't have the Ethernet Network Adapter configured, but I have made sure the addresses match the values when "BO3NETGM.ELF" is run. I guess ElHecht tested it when he made the patch.

Project Snowblind PAL. CRCs Fixed 

---

patches/SLUS-20904_536FEB77.pnach

Fixes the broken patch formatting on spongebob the movie game

Fixes patch formatting for Spongebob The Movie

---

patches/SLPS-25338_26D1C561.pnach
patches/SLPS-25339_26D1C561.pnach

- Rewrote `[No-interlacing]` patch to fix hanging up after some missions.
- This change is only for NTSC-J Armored Core Nexus (Both discs).

Fix hanging up after mission levels

---

patches/SLES-53502_EFC63B51.pnach

This disc has SLES-53502 as serial-code, not SLES-53505.
SLES-53505 is "Beat Down - Fists of Vengeance",
both according to GameIndex and redump.
http://redump.org/disc/24233/
http://redump.org/disc/520/

Minor Typo fix

---

patches/SCES-50294_B590CE04.pnach
patches/SLES-50330_021396FD.pnach
patches/SLES-50330_581954FC.pnach
patches/SLES-51061_26954C46.pnach
patches/SLES-51061_C498A04F.pnach
patches/SLES-51061_CFCB0D20.pnach
patches/SLES-52541_A1B3F232.pnach
patches/SLES-52541_B440A8FE.pnach

As of this version: https://github.com/PCSX2/pcsx2/pull/10821 Patches can no longer be disabled per game. These types of patches that are only limited to eliminating the sceGsSetHalfOffset routine were a good fix in old versions but now they have become obsolete, do not improve anything and do worsen the textures and letters, so to keep the games with the least alteration I remove. following that I have verified are no longer necessary.
In Gran Turismo 3 we see that in automatic and the default interlacing modes of pcsx2 they do not act correctly so a patch would be needed.
Old patch that eliminates the routine sceGsSetHalfOffset 
New patch enables progressive interlacing, keeps the sceGsSetHalfOffset routine unchanged, the image does not shake and the scrolling of the letters looks …

Remove unnecessary No-Interlacing patches

---

patches/SLPM-66211_7EC8A8A3.pnach

- Fixes gametitle which had a typo, missing the P in Peter.
- ~~Fixes a commented patch which was the only patch in the pnach file, meaning the widescreen patch did nothing.~~ Removed this change as it is impossible for me to test currently. For anyone interested, [this line is here](https://github.com/PCSX2/pcsx2_patches/blob/955a9d824f8bf898618d582ba0136496102157f6/patches/SCES-50244_71E38F05.pnach#L10).
Full credit to @pgert for reporting these in #304. I did not include those in those changes as these were both issues that would be undetected by the CI action so did not want to make it confusing.

Fixes commented patch & incorrect game title

---

patches/SLUS-21845_7FAE77BE.pnach

Breaks sprite overlap in some scenes.

WS: Disable SMT DS 2 WS patch

---

patches/SCES-51608_2479F4A9.pnach
patches/SCES-52460_12804727.pnach

Currently breaks text rendering when switching to 60hz or progressive scan.

WS: Disable Jak 2 PAL WS patch

---

patches/SLUS-21299_A719D130.pnach

I updated the patch for Dynasty Warriors 5: Xtreme Legends (SLUS-21299) with the CRC A719D130 to include the cutscene fix drobovik shared. I also included the code to unhide Musou/Free mode as a separate patch. 
This is related to the issue from here: https://github.com/PCSX2/pcsx2_patches/issues/335

Dynasty Warriors 5: Xtreme Legends (SLUS-21299) patch updated to include cutscene fix and enable Musou/Free mode

---

patches/SLES-51970_763D3BF9.pnach

Causes TLB misses on game boot.

WS: Remove 480p code from BFBB patch

---

patches/SLES-50812_CB179BA2.pnach
patches/SLES-50813_295D2F91.pnach
patches/SLES-50965_CCF57297.pnach
patches/SLUS-20336_015CB6F4.pnach

It lacks a render fix, when moving around the stage the objects do not appear on the sides.

Disable Spider-man the movie WS patch

---

patches/SCES-52004_6624A78C.pnach
patches/SCUS-97328_77E61C8A.pnach
patches/SCUS-97402_CAAEC49C.pnach
patches/SLUS-20910_5D0244D3.pnach
patches/SLUS-21355_60A42FF5.pnach

Cleans up a mistake I made bringing over some GT4 patches and removes the 32 bit color depth patch as it causes the blue rectangle of death on the left hand side of the screen also removes the Midnight Club 3 Dub Remix 16:9 HUD fix as it apparently causes FPS issues and doesn't actually function correctly and brings over Silents Test Drive Eve of Destruction shoulders control mapping patch.

Patches: Various fixes

---

patches/SCUS-97328_77E61C8A.pnach

`Adjusted trigger sensitivity` and `Full Trigger Sensitivity` are practically identical cheats.

Gran Turismo 4 (SCUS-97328): Removed a duplicate cheat

---

patches/SCUS-97502_FF9C0E93.pnach

The patch only enables 480p in races. Menus are still 480i so disabling interlace handling causes issues in these screens.

Patches: Fix Tourist Trophy no interlacing patch.

---

patches/SLES-53100_FE0030D6.pnach
patches/SLUS-21091_FE0030D6.pnach

Both versions cause SPS in the intro and sewer levels (that we know of).
Disabling until they can be fixed.

Disable Scooby Doo Unmasked WS patches

---

patches/SLES-51153_1A957202.pnach
patches/SLUS-20575_BC910F04.pnach

Disables patches for LEGO Island Xtreme Stunts.
These cause SPS.
This is the second set by Arapapa I've had to disable this week for SPS, can we PLEASE make sure these patches work before you submit them, you didn't even have to test far with this one, literally the main menu is broken.

Disable Lego Island Xtreme Stunts patches

---

patches/SLUS-20954_E798B2D5.pnach

Hack is from:
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=629916#pid629916
Hack tested and approved by EnthusiaFan7225:
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=629962#pid629962

Hot Wheels STC - new WS hack

---

patches/SLES-51058_54854C71.pnach

PAL Progressive scan instead of NTSC Progressive Scan forcing 60 FPS on the user and having the consequence of de-syncing all Maken Shao cutscenes to end faster than they should.
It should resolve #380

Update SLES-51058_54854C71.pnach for proper PAL Progressive scan

---

patches/SCUS-97330_644CFD03.pnach

Causes black texture flicker in desert areas.
Closes #391

WS: Disable Jak 3 NTSC WS patch

---

patches/SLES-51554_904B7BA0.pnach

Breaks splitscreen multiplayer.

WS: Disable Cel Damage Overdrive WS patch

---

patches/SLUS-20219_D5D560FF.pnach

Sound fix for stuttering echo-repetition glitchy audio looping during FMV/cut-scenes.  
I confirmed that this code fixes the long-standing audio bug.  The audio stuttering problem is progressively degenerative without this code, and CANNOT be fixed by the commonly offered config changes. 
Username who posted at the wiki is kozarovv, I cited them as author.
https://wiki.pcsx2.net/Time_Crisis_II

Sound glitch fix patch for Time Crisis 2

---

patches/SCUS-97133_E21404E2.pnach
patches/SCUS-97408_E78971DF.pnach

60 FPS "asasega Patches" will be added for “The Getaway” and "The Getaway Black Monday" [NTSC-U]. Games runs very well in 60 FPS and it is completely playable. I have tested it several times.

Add 60 FPS Patches for "The Getaway" and "The Getaway Black Monday" [NTSC-U]

---

patches/SLES-51908_8176235A.pnach
patches/SLPM-65723_960D74D7.pnach
patches/SLUS-20738_901ECEFC.pnach

Updating to a full widescreen that includes, entire hud, any menu and any font
Older patch
Updated patch
Older patch
Updated patch
Older patch
Updated patch
Older patch
Updated patch

Update Van Helsing to a full widescreen patch

---

patches/SCUS-97112_087A3C85.pnach
patches/SLES-53411_B3589D67.pnach
patches/SLPS-20488_B2486AF4.pnach
patches/SLUS-20893_158FA006.pnach

This PR adds support for Widescreen
[Kuon Spanish Fan Translation](https://www.romhacking.net/translations/3970/)
Before
After
[The Tairyou Jigoku Spanish Fan Translation](https://www.romhacking.net/translations/6317/)
Before
After
[Extermination Undub](https://archive.org/download/extermination_undub_patch)
Before
After
[Way of the Samurai 2 Undub](https://archive.org/download/way_of_the_samurai_2_undub_patch)
Before
After

Add patches for Translations and Undubs

---

patches/SLUS-20670_D600925B.pnach

Causes objects and black triangles or bars to appear at the edges of the screen.

WS: Disable The Great Escape WS

---

patches/SLUS-21050_BEBF8793.pnach
patches/SLUS-21242_D224D348.pnach
patches/SLUS-21596_8C9576A1.pnach

Burnout 3 Takedown
- The file was missing its `gametitle=`
- The widescreen patch was incomplete, now it has been taken from its [original repository](https://github.com/AeroWidescreen/PCSX2-Cheats/blob/main/Burnout%203%20Takedown/SLUS-21050/Widescreen%20Fix/SLUS-21050_BEBF8793_widescreen.pnach) and completed.
- [60 FPS menus] now specify what each line of the patch does
- [60 FPS crashes] replaced that old patch with a newer and simpler one.
- Nehalem patches used to be `patch=1` now they are changed to `patch=0`, so that they match their [original repository](https://github.com/Nahelam/PS2-Game-Mods/tree/main/Burnout%203%20Takedown) (this does not bring any negative change as they were always `patch=0`).
Burnout Revenge
- The author's name has been corrected from Nahelam to Nehalem.
- …

Burnout Takedown/Revenge/Dominator formating

---

patches/SLUS-21065_F5C7B45F.pnach

That's quite an omission this hasn't been added yet, so I'm filling the gap.
NFSU2 (NTSC-U, SLUS-21065). Just tested thoroughly on v2.1.174. Requires EE 180% OC, otherwise frames dip down in the city center area.
There is _only one non-gamebreaking_ curiosity: whenever the player's car is being parked into a shop/the garage, the in-game driving-in animation is sped up; this has no other side effects, in fact, quite amusingly feels like a QoL.
I don't know whether this insignificant glitch would be considered for a pull decline or not.
So far, this has not been breaking any game physics at 60 FPS, although on the PC port it gets wonky at 120.

Need for Speed Underground 2 (SLUS-21065) various patches

---

patches/SLES-50677_DEFA4763.pnach
patches/SLUS-20659_004B2E96.pnach
patches/SLUS-21390_17493C04.pnach

Disables WS patches for Urban Chaos and Shadow Hearts PAL as they cause SPS and graphical issues and disables piglets big games WS until I can fully investigate the game and it's issues.

WS: Disable more problematic patches

---

patches/SLUS-20766_1C6C1B71.pnach

- The undub patch was updated a few months ago and with that update the CRC changed again, so this PR adds support for this new Undub v1.0.2 (1C6C1B71) ~~basically using the same patches as Undub v1.0.1 (1C6C1DB6).~~
- So the support for the old v1.0.1 is removed, in order not to fill this repository with unnecessary CRC's, leaving only the support for the most recent version of this romhack.
- as well as this PR serves as a follow up of #424
since that PR forgot to disable the broken 60fps patch for the Undub patch
~~i would also like to have the opinion of a moderator~~
~~1. I should remove support for the old undub patch v1.0.1 (1C6C1DB6) from Nov 1, 2022 and only support for the latest undub patch v1.0.2 (1C6C1B71) from May 17, 2024?~~
~~2. Or leave it as it is for possible players …

Fatal Frame 2 Undub - Patches update

---

patches/SLES-50054_8CB701AF.pnach
patches/SLES-50071_831078BD.pnach
patches/SLPM-66675_F266B00B.pnach
patches/SLUS-21005_DA0535FD.pnach
patches/SLUS-21059_652050D2.pnach

Midnight Club - Street Racing: Fixed car selection
Tekken 5 USA: Added 480p patch, enables native 480p mode from start
Kingdom Hearts II USA and JAP Final Mix+ version: 60 FPS patch was missing in these versions, now they are complete

Add patches and fixes

---

patches/SLPS-25784_B1B6E33D.pnach

Causes the game to be double speed.

NI: Disable NI patch for ACE 3 The Final

---

patches/SLPM-65897_1C087362.pnach

This ws patch removes rendering issues of the previous patch, e.g. misaligned lights

Fixed widescreen patch for Racing Battle C1 Grand Prix [SLPM-65897]

---

.github/scripts/validate_patches.py
.github/workflows/pack_patches.yml
.github/workflows/validate_patches.yml

This PR does the following:
1. The validation script got some syntax warnings fixed and now explicitly reads the patch files as UTF-8. This makes the validation script work correctly also on Windows.
2. Outdated actions have been updated. `marvinpinto/action-automatic-releases` is deprecated and should be replaced, but one of the possible replacements, `softprops/action-gh-release`, has its fair share of issues - and currently cannot be used by us properly due to https://github.com/softprops/action-gh-release/issues/191.

Scripts: Fix the validation script

---

patches/SLUS-20176_D813AF38.pnach

Reposting my old improvement for the widescreen patch from here:
<https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=612346#pid612346>
Improved upon Arapapa's widescreen patch for NASCAR Heat 2002 (NTSC-U) to allow for specifying negative left/right margins. Albeit counter-intuitive, this allows to properly align HUD to 16:9 boundaries instead of having all elements stuck at their 4:3 boundaries.

NASCAR Heat 2002: Allow specifying negative margins

---

patches/SLUS-20296_5D8B63C1.pnach

Patches broke shadows.
See https://forums.pcsx2.net/Thread-Bug-Report-Kao-the-Kangaroo-Round-2-NTSC

WS: Disable Kao the Kangaroo Round 2 patches.

---

patches/SLUS-21385_D850707E.pnach

The following is a patch correction for the "SLUS-21385_D850707E.pnach", also known as the NTSC-U version of "The Godfather". It's based off Arapapa's widescreen patches. Here's what I'm correcting:
**Before:**
Originally, while using Arapapa's 16:9 Widescreen Patch, the FOV correction would cause the player model to look bigger making its head invisible (therefore impossible to edit, without disabling patches and rebooting).
Also, weapon models would obscure their names and ammo count, making it difficult to keep track of remaining ammo.
**After:**
With these corrections, the player model's head is no longer obscured during character creation or editing.
Finally, weapon models no longer obscure their information.
**Miscellanous:**
Out of desire to preserve the original feel of the game …

Changes to Widescreen Patch in The Godfather for better FOV and correcting minor gameplay issues

---

patches/SLPS-25028_F9D5C6A6.pnach

fix a bug that some elements are not correctly modified.
---
Before:
After:

Tokyo Xtreme Racer 0 (J): Fix widescreen patch

---

patches/SLUS-21045_CC6CBF20.pnach

60 FPS patch by asasega. Game runs perfectly well at 60 FPS. Occassions where it doesn't are barely noticeable around 56–60 FPS and only for a few short moments, and these can be remedied by overclocking up to 130 or 180%. Areas which would slow down the game considerably are handled correctly by the game itself, which sets itself back to 30 FPS while maintaining the correct game speed. (The only example I was able to find of this is the area in Mission 1 which has a guard tower and a vehicle repair garage.) Tested thoroughly in Missions 1–4 for about two hours. All 14 missions except Mission 7 (a boat ride) and Mission 13 (a helicopter ride) have the exact same core gameplay, and 7 and 13 barely diverge from this (you are not actually piloting either vehicle). Game makes minimal use of …

Conflict: Vietnam - Add 60 FPS patch (tested)

---

patches/SLUS-21129_A33AF77A.pnach

**Adds undub patch that forces Japanese voices at all times**
this game has a built-in option to activate the japanese voices, but this option always needs to be enabled manually each time the game is launched as it is disabled when the game is closed.
But with this patch it will always force the use of the japanese voices automatically.

Tenchu: Fatal Shadows - Add Undub patch

---

patches/SLUS-20946_2C6BE434.pnach
patches/SLUS-20946_399A49CA.pnach

The current widescreen patch, while functional, has the HUD and the radar unaffected. I include pnach files for 1.03 and 3.00 that make the widescreen appear more like ThirteenAG's widescreen mod on PC, thus fixing the HUD and radar. It also has the added benefit of not glitching the emergency vehicles. I also include a Silentpatch lite that adds cosmetic and QOL enhancements, similar to the PC version, while leaving game mechanics otherwise untouched, so it wouldn't trigger RetroAchievements' anticheat system.
1.03
3.00
(For best results, turn the ingame widescreen option on, but that does not affect the radar/HUD whether on or off)

GTA San Andreas Widescreen improvement and Silentpatch Lite for 399A49CA and 2C6BE434

---

patches/SLUS-21782_DEDC3B71.pnach

I took the existing 16:9 patch, and changed its values to work better with 16:10 displays.
Things that were changed compared to 16:9 patch:
- Game FOV (That's what //16:10 stands for)
- HUD fix - adjusted dialogue portraits
- FMV's - slight changes to size
- Persona arts - size + corrected position to be closer to how it was in 4:3 Characters art - Changed size
The changes were all tested and nothing seems to be broken (at least I didn't notice anything)
Screenshots of the patch:

Shin Megami Tensei: Persona 4 (SLUS-21782) 16:10 Widescreen patch

---

patches/SLPM-65897_1C087362.pnach
patches/SLPM-65897_9C4C9611.pnach

Adds widescreen rendering to mirrors and reflections
Also adds a pnach file for the English patched version (CRC 9C4C9611)
https://github.com/igorciz777/RBC1GP-Translation-Pipeline/releases/

Fixes to RB:C1GP [SLPM-65897] WS patch + pnach for English patched version

---

patches/SLES-54439_891F223F.pnach
patches/SLPM-66375_C5DEFEA0.pnach
patches/SLUS-21115_21068223.pnach

Disable post-processing effect to improve the visual quality bothered by the excess of post-processing effect and filters that are not well rendered and do not look good on modern monitors, all this without altering the essence and art design of Okami.
This patch disable:
- Excessive blur/bloom
- Ghosting
- Noise filter

Disable all post-processing effect in Okami.

---

patches/SLES-53073_DCD7104E.pnach

This patch restores fog effects to the European version of Michigan. This is a plot-critical effect, but carelessly cut from the game's update loop in what appears to be a bug fix.
Implementation details/notes in patch.
Before:
After:

Add Michigan: Report from Hell fog restoration patch

---

patches/SLPM-65409_EE61D258.pnach

Gives the player glasses so that they can properly fly a helicopter.
Must be enabled outside a mission to properly stop the depth of field task from spawning.
Before:
After:

Add Air Ranger 2 Plus anti-blur patch

---

patches/SLUS-20398_4C168567.pnach

Just a small patch file due to a request by silent, this converts an xdelta I made to a pnach which can be mix and matched without modifying the game.
This adds five switches:
1. No-Interlacing
Sets the game to use progressive mode upon boot; half vertical resolution
2. Force Hi-Quality Car Models
Cars in races/overworlds have pretty aggressive LODs, and this disables that. Additionally, this shows 3D wheel models on cars in the overworld when previously 3D wheels were never visible on cars in the overworld (to be specific, this makes the spokes parts of the wheels 3D, instead of a 2D texture).
3. Anti-Blur
This removes a ghosting effect in the game, which was implemented by taking the last two frames and overlaying it over the current frame with some transparency.
4. Analog steering
This …

Road Trip (USA) Patches (Progressive, widescreen, hi-quality cars, anti-blur, analog steering)

---

patches/SLES-51967_FDA10318.pnach
patches/SLKA-25136_C5D0EBD2.pnach
patches/SLPM-65471_4608D01A.pnach
patches/SLUS-20811_CB99CD12.pnach

Featured fixes:
* Fixed the unlock requirements for Magazine 22, which is awarded for setting a Drift Track record. The magazine is now awarded for beating the average lap high score, ensuring the requirements are fair regardless of the number of laps in the event.
* Drift events now display the total score as their High Score instead of style points.
* Fixed a buffer overflow issue in the UI display of opponent names. This resolves a bug where Samantha's name appeared corrupted during races.
Same as in https://cookieplmonster.github.io/mods/need-for-speed-underground-ps2/#silentpatch, submitted to the patch db so it can be used with RetroAchievements Hardcore Mode.

NFS Underground: SilentPatch

---

patches/SLES-50953_68DAAF46.pnach
patches/SLPS-20083_62566E6A.pnach

Adds 16:9 widescreen patches for the European and Japanese releases of Air Ranger: Rescue Helicopter.
Needs a reset when applied.
Before:
After:

Air Ranger: Rescue Helicopter widescreen patches

---

patches/SLUS-21120_2373FD16.pnach

Does what it says on the tin, enables Psychonauts to be played in 60fps. Requires pretty beefy hardware and EE Cycle Rate overclocking.

Add Psychonauts 60FPS patch

---

patches/SLUS-20307_4783F7ED.pnach

This patch disables the very subtle depth of field effect. It's not very well implemented in the original game, as it mainly just serves to add shimmering to the tops of distant structures. It's also barely visible at native resolution.

Burnout 1 Depth of Field patch

---

patches/SLUS-21560_D2790A77.pnach

Seems to break the eyes on models.

WS: Disable NTSC Family Guy WS

---

patches/SLES-50268_B5BF9785.pnach
patches/SLUS-20056_E3ADA82E.pnach

Adds 50/60fps patches to SpyHunter. Also adds widescreen patches, replacing the US patch, which appears to have culling issues.
The original patch seems to have conditions to fix culling issues, but these affect addresses which are in the heap (0x196FE00 and 0x196FDE0) so if this worked at one point, it no longer does.
Old patch:
New patch:

SpyHunter Widescreen and 50/60 FPS patches

---

patches/SLES-50650_CD3ED649.pnach
patches/SLPM-65059_35FB8EE2.pnach
patches/SLUS-20219_D5D560FF.pnach
patches/SLUS-20221_7FBCDA34.pnach
patches/SLUS-20645_7290669C.pnach

Adds GunCon2 flash effect removal when firing guns for the following titles:
Resident Evil - Survivor 2 - Code - Veronica (EU)
Gun Survivor 2 - BioHazard Code - Veronica (JP)
Vampire Night (US)
Time Crisis 2 (US)
Time Crisis 3 (US)
Might port them to other regions sometime.

GunCon2 Flash Removal for various games

---

patches/SLUS-21273_8BE5DFF3.pnach
patches/SLUS-21661_8FCCB5D9.pnach

Disables Matrix Path of Neo NTSC 60 fps patch and Ben 10 Protector of The Earth 60 fps as they both break aspects of the games.
Fixes #524

Disable more 60 fps patches

---

patches/SLUS-21050_BEBF8793.pnach

Disabling Motion Blur and Bloom are essential to have a smoother Burnout 3 experience on lower end devices, and sometimes for even a better experience in general i.e disabling Motion Blur.
The original repo had all these speedhacks in one cheat ( https://github.com/danpsr/burnout-3-pcsx2-speedhack/blob/main/BEBF8793.pnach ). I separated the Motion Blur and Bloom Disabling Cheats as individual cheats added them in this patch.
Essential cheats, specially for someone who wants to play Hardcore RetroAchievement for this game, but faces lags with the default Motion Blur.

"Burnout 3 - Takedown" - Disable Motion Blur & Bloom by escape209

---

patches/SLES-51930_09736614.pnach

Adds NTSC mode patch to Road Rage 3 -- also has the side effect of correcting game speed because this is one of those bad PAL ports. As far as I know nothing else needs to be adjusted to correct for the change in game speed. Even the in-game timer has 8 and 1/3rds seconds pass in 10 seconds in the original PAL mode.
Also changed the no-interlacing patch to use patch=0 since it patches the code segment.

Add NTSC Mode patch for Road Rage 3

---

patches/SLUS-21474_18834BA2.pnach

Added a 60fps patch and tested it for a few minutes. There seem to be no immediate issues and considering there's also a 360 and PC port (with no reported 60fps issues) I assume there should be no issues here.

Add 60fps patch for History Channel Civil War (US)

---

patches/SLES-52472_0AF4683D.pnach

Adds patches to remove interlacing artefacts and force the game to NTSC upon startup (after reaching the title menu, you can scroll down to options and change to NTSC, but this patch just does that for the user).

Add de-interlace and ntsc mode patches for Project Minerva Professional (EU)

---

patches/SLUS-21109_0520A26D.pnach

The original release of **Mashed** (SLES-52446) did not have native widescreen support, but updated releases **Mashed: Fully Loaded** (SLES-53152) and **Drive to Survive** (SLUS-21109) have native WS available from the game options. This patch does the same thing visually, and stacks on top of the native support.
In-game Widescreen Off, patch enabled:
In-game Widescreen On, patch enabled:
In-game Widescreen On, patch **disabled**:

Drive to Survive: Remove a pointless widescreen patch

---

patches/SLUS-20114_6D0D9F1F.pnach

This is a modification of the patch for the previous pull request which only uncapped the framerate, but did not touch timestep: https://github.com/PCSX2/pcsx2_patches/pull/533
Timestep (and game speeds calculated from it) are only calculated on boot, so this patch manually recreates each of those calculated values set in code.

Add Simpsons Skateboarding 60fps patch

---

patches/SLUS-21242_D224D348.pnach

Disabling Motion Blur and Bloom are essential to have a smoother Burnout Revenge experience on lower end devices, and sometimes for even a better experience in general i.e disabling Motion Blur.
The original repo had all these speedhacks in one cheat ( https://forums.pcsx2.net/Thread-Burnout-Revenge-USA-Speedhack-Patch ). I separated the Motion Blur and Bloom Disabling Cheats (leaving the Fog Speedhack) as individual cheats added them in this patch.
Essential cheats, specially for someone who wants to play Hardcore RetroAchievement for this game, but faces lags with the default Motion Blur.

Burnout Revenge (USA) - Disable Motion Blur and Bloom by escape209

---

patches/SLPM-67519_D2F77DF2.pnach
patches/SLUS-20138_D2F77DF2.pnach

The NTSC-K disc seems to be identical to the NTSC-U disc.
Not only do they have the same CRC, but they had the same WS hack by ElHecht & icup321.
Consequently it should be resonably safe to apply the new WS hack
by RibShark (Rib) from #541 for the NTSC-K disc as well.
Testing & feedback appreciated.
Also formated the hack for both discs, and re-added the old hack (though commented out) to avoid confusion.
@RibShark - can you test the formating (with 21:9)?

Rayman 2 - porting and formating

---

patches/SLUS-21813_5A6A935D.pnach

This patch adds 60fps functionality to the US version of 007 - Quantum of Solace. The patch conditionally switches to 30fps when .pss files run, to prevent them running too quickly. It also affects the weapon recoil compensation, which seems to be affected by framerate, to recreate similar recoil behavior as if the game was running at 30fps.

Add 60fps 007 Quantum of Solace US patch

---

patches/SLES-53971_9C593C78.pnach
patches/SLUS-21406_D850707E.pnach

Tested patches:
**The Godfather - Collector's Edition NTSC-U SLUS-21406 D850707E**
- Widescreen (Tested :heavy_check_mark:)
- Remove Blackbars (Tested :heavy_check_mark:)
- 60 FPS (Tested :heavy_check_mark:)
**The Godfather NTSC-U SLUS-21385 D850707E**
- 60 FPS (Tested :heavy_check_mark:)
**The Godfather PAL-S SLES-53971 9C593C78**
- Update Widescreen (Tested :heavy_check_mark:)
- NTSC Mode (Tested :heavy_check_mark:)
- Update FPS patch that causes annoying lag (Tested :heavy_check_mark:)
The old widescreen patch in the PAL-S version causes graphical problems, and some of them have already been exposed by El_Patas in the widescreen forum. [https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=376849#pid376849](https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=37 …

The Godfather patches support update

---

patches/SLES-52541_A1B3F232.pnach
patches/SLES-52541_B440A8FE.pnach
patches/SLES-52927_B61F872C.pnach
patches/SLUS-20946_2C6BE434.pnach
patches/SLUS-20946_399A49CA.pnach

We've reverted the cutscene improvements to their original values. I'll take this opportunity to add the PAL-G version.
Fixes #551 
Note: Improved the "remove ghosting affects" patch on PAL versions.

GTA San Andreas: revert values original in cutscenes

---

patches/SLES-52541_A1B3F232.pnach
patches/SLES-52541_B440A8FE.pnach
patches/SLES-52927_A3EF1321.pnach
patches/SLES-52927_B61F872C.pnach
patches/SLPM-55292_9E18263C.pnach
patches/SLPM-65984_60FE139C.pnach
patches/SLUS-20946_2C6BE434.pnach
patches/SLUS-20946_399A49CA.pnach

This PR introduces two changes to GTA San Andreas patches:
1. `Remove Radiosity Filter` patch in fact broke all the post effects, including the color filter, radiosity, heat haze, night and thermal vision, motion blur, and the underwater ripple effect. We have better alternatives now, so it makes no sense to keep a cheat that breaks the game.
It's possible, however, that some people were using this patch to remove the yellow tint and make the game look more like the PC port. For this reason, I introduced a new `Remove Color Filter` patch that does the removal properly. The new patch **doesn't** remove the ghosting effect caused by radiosity, but it can safely be used with the other patch to also remove that, if users desire so.
2. The current `Remove Ghosting Effects` patch from …

GTA San Andreas: Changes to postfx removal patches

---

patches/SLES-53390_FDD12792.pnach
patches/SLES-53391_FDD12792.pnach
patches/SLPM-66404_ADFF13DF.pnach
patches/SLUS-20870_FDD12792.pnach
patches/SLUS-21285_FDD12792.pnach

Updated patches. I found the rendering solution for widescreen a while ago. The only thing missing are the flashes that appear in the game when an enemy fires lightning bolts or in the storm where we fight Venom at the beginning and end of the game. These flashes are in 4:3. I don't think they're very relevant, and all things considered, the positives outweigh the negatives.
I think it's a good time to add it to the repository so we can enjoy it.
Fixes #556

Ultimate Spider-man update patches

---

patches/SLUS-20383_B6580DA4.pnach

Adds framerate hack to default the framerate at 60fps, so it no longer has the wait time for the cap to adjust after overclock.

Add framerate hack for Vexx (NTSC-U)

---

patches/SCES-53133_FB0E6D72.pnach
patches/SCES-54206_44A8A22A.pnach
patches/SCUS-97399_D6385328.pnach
patches/SCUS-97481_2F123FD8.pnach

This patch adds the option to skip cutscenes, which is especially useful for speedrunners. It has been tested on Vulkan with version 2.2.0, and no bugs or crashes were observed.
God of War PAL-M  (SCES-53133_FB0E6D72)
God of War 1 USA  (SCUS-97399_D6385328)
God of War 2 USA  (SCUS-97481_2F123FD8)
God of War 2 PAL-M  (SCES-54206_44A8A22A)
Details:
Enables cutscene skipping by pressing the action button
To God of War 1 and God of War 2 (USA and EU versions).
Saves approximately 1 hour and 15 minutes in God of War 2.
Saves approximately 51 minutes in God of War 1.
Improves gameplay flow without affecting game stability.
[Patchs.txt](https://github.com/user-attachments/files/20402877/Patchs.txt)

Add Enable Skip Cutscenes Patch for God of War 1 And 2

---

patches/SLUS-21109_0520A26D.pnach

This reverts commit 0e484342c8daf0068b498a3d32ceedf39bf8b1c6.
I recently removed this widescreen patch as the game has native widescreen, **but** it turns out it's broken on the first boot. Even though this patch is imperfect as it reinvents widescreen instead of toggling the in-game option, I'm reinstating it for now until I get some time to investigate the actual issue and replace it with a proper toggle.

Revert "Drive to Survive: Remove a pointless widescreen patch (#539)"

---

patches/SLUS-21090_190DF20A.pnach

Levels like 1-2 have scrolling sections where the player jumps over vehicles and they can die if they land on the road. With the current widescreen fix enabled, if the player dies outside of the 4:3 screen area, the game softlocks and they won't respawn.
This bug renders the game essentially unplayable.

Alien Hominid: Disable the widescreen fix breaking respawning

---

patches/SCES-51248_531061F2.pnach
patches/SLPM-65995_08E89523.pnach
patches/SLUS-21018_35CB5180.pnach

**Explanation:** This patch disables the blur caused by the depth of field effect. Everything has been tested and I can confirm that it doesn't cause any problems.
Patches:
Disable Blur
- **Dog's Life PAL-M SCES-51248 531061F2** (Tested :heavy_check_mark:)
- **Dog's Life NTSC-J SLPM-65995 08E89523** (Tested :heavy_check_mark:)
- **Dog's Life NTSC-U SLUS-21018 35CB5180** (Tested :heavy_check_mark:)
Additional 60 FPS patch for **NTSC-J**

Disable blur patch for Dog's Life

---

patches/SLUS-20887_058849D1.pnach

This adds the ability to skip the unskippable cutscenes in Attack of the Twonkies. It might take half a second or so to skip the cutscene after pressing START or X -- due to the way cutscene-processing logic is set up, it'd be a bit funky to make it instantaneous.

Add Skippable Cutscene patch to Jimmy Neutron Attack of the Twonkies US

---

patches/SLES-51249_EE3BCA71.pnach
patches/SLES-52179_973793E8.pnach
patches/SLES-52835_40033F92.pnach
patches/SLES-53046_EDE9DD5C.pnach
patches/SLES-53553_22DC8EAC.pnach
patches/SLES-53797_A0DC603B.pnach
patches/SLES-54031_CC39A3E6.pnach
patches/SLES-54126_E393DFE5.pnach
patches/SLES-54150_85495C17.pnach
patches/SLES-54159_3E9B19C2.pnach
patches/SLES-54364_5415FA68.pnach
patches/SLES-54757_F654BFDC.pnach
patches/SLES-55448_528C8054.pnach
patches/SLES-55546_B6BA0E59.pnach

**Tested NTSC Patches** :heavy_check_mark: 
- Castleween PAL-M SLES-51249 EE3BCA71
- Kaan - Barbarian's Blade PAL-M SLES-52179 973793E8
- The Mummy - The Animated Series PAL-M SLES-52835 40033F92
- Counter Terrorist Special Forces - Fire for Effect PAL-M SLES-53046 EDE9DD5C
- 007 - From Russia with Love PAL-M SLES-53553 22DC8EAC
- FIFA Street 2 PAL-M SLES-53797 A0DC603B
- The Da Vinci Code PAL-M SLES-54031 CC39A3E6
- Family Guy - The Video Game PAL-M SLES-54126 E393DFE5
- Bionicle Heroes PAL-M SLES-54150 85495C17
- Eragon PAL-M SLES-54159 3E9B19C2
- Curious George PAL-M SLES-54364 5415FA68
- Transformers - The Game PAL-G SLES-54757 F654BFDC
- Indiana Jones and the Staff of Kings PAL-M SLES-55448 528C8054
- The Secret Saturdays - Beasts of the 5th Sun PAL-M SLES-55546 B6BA0E59
Added 50/60 …

NTSC patches (part 1)

---

patches/SLUS-21580_166ADC2E.pnach

Patch that adds `16:9`, `16:10` and `21:9`.
16:9 example:

Widescreen Patches for MTV Pimp My Ride

---

patches/SLUS-21731_A8D83239.pnach

The purpose of this PR is to improve the 60fps patch, as the current one seems to have some issues with the FMVs.
https://retroachievements.org/forums/topic/18293?comment=299716#299716
Source of the patch: https://wiki.pcsx2.net/Silent_Hill:_Origins

Silent Hill Origins (NTSC-U) - Improved 60FPS

---

patches/SLES-50821_22E91837.pnach

Appears to break mirror rendering.
With:
Without WS:

WS: Disable project zero PAL WS

---

patches/SCUS-97130_9C8D0998.pnach

Does what it says on the tin. There's a few FMVs (at boot and if you sit on the title screen for a bit) but I couldn't figure out how to remove interlacing artefacts in that mode.

Add deinterlacing patch for Hot Shots Golf 3 (USA)(v2.00)
